import{jsx as _jsx}from"react/jsx-runtime";import{useEffect,useRef}from"react";import{useFrame,useThree}from"./837f1a07-de45-4d4e-8701-0528f7768e14.js";export const ENTER_ANIMATION_OPTIONS=["none","slideBottom","slideTop","slideLeft","slideRight","scaleUp","drop","spin","tilt","rise","dolly","orbit","crane","focusPull"];export const ENTER_ANIMATION_TITLES=["None","Slide • Bottom","Slide • Top","Slide • Left","Slide • Right","Scale Up","Drop & Settle","Spin In","Tilt To Face","Rise From Flat","Dolly In","Orbit Reveal","Crane Down","Focus Pull"];const PI=Math.PI;const ENTER_TRANSFORMS={// Layer A
slideBottom:{position:[0,-4,0]},slideTop:{position:[0,4,0]},slideLeft:{position:[-4,0,0]},slideRight:{position:[4,0,0]},scaleUp:{scale:.2},drop:{position:[0,5,0],bounce:true},spin:{rotation:[0,PI*2,0]},tilt:{rotation:[0,-PI/2,0]},rise:{rotation:[PI/2,0,0]},// Layer B (simulated camera moves)
dolly:{position:[0,0,-4],scale:.6},orbit:{rotation:[0,-PI*.66,0]},crane:{rotation:[PI*.6,0,0],position:[0,1.2,0]},focusPull:{fov:2}};export function isTransformAnimation(type){return Boolean(ENTER_TRANSFORMS[type]);}// --- Spring -----------------------------------------------------------------
// Tuned subtle: ~1s settle at speed 1 with a hint of overshoot. Integrated with
// fixed substeps so high stiffness stays stable regardless of frame rate.
const SETTLE_EPS=5e-4;const SUBSTEP=1/120;function springStep(value,velocity,target,omega,zeta,dt){let v=value;let vel=velocity;let remaining=dt;while(remaining>0){const step=Math.min(SUBSTEP,remaining);const accel=-omega*omega*(v-target)-2*zeta*omega*vel;vel+=accel*step;v+=vel*step;remaining-=step;}return[v,vel];}/**
 * Drives the wrapper group (and, for focusPull, the camera fov) from the
 * animation's start offset back to rest. No-op for "none" — the group simply
 * stays at identity so Float/OrbitControls behave exactly as before.
 */export function useEnterTransform({groupRef,type,enabled,speed=1,delay=0}){const camera=useThree(state=>state.camera);const cfg=ENTER_TRANSFORMS[type];const stateRef=useRef(null);const elapsedRef=useRef(0);const startedRef=useRef(false);const doneRef=useRef(false);// Reset whenever the animation changes so a re-selection replays cleanly.
useEffect(()=>{stateRef.current=null;elapsedRef.current=0;startedRef.current=false;doneRef.current=false;},[type,enabled,speed,delay]);useFrame((_,rawDelta)=>{const group=groupRef.current;if(!group||!enabled||!cfg||doneRef.current)return;const dt=Math.min(rawDelta,1/30);// Lazily capture the resting fov once the real perspective camera exists.
if(!startedRef.current){const restFov=camera.isPerspectiveCamera?camera.fov:null;const startFov=cfg.fov!=null&&restFov!=null?restFov*cfg.fov:restFov??0;stateRef.current={pos:[cfg.position?.[0]??0,cfg.position?.[1]??0,cfg.position?.[2]??0],rot:[cfg.rotation?.[0]??0,cfg.rotation?.[1]??0,cfg.rotation?.[2]??0],scale:cfg.scale??1,fov:startFov,vel:[0,0,0,0,0,0,0,0],restFov};startedRef.current=true;}const st=stateRef.current;const applyTransform=()=>{group.position.set(st.pos[0],st.pos[1],st.pos[2]);group.rotation.set(st.rot[0],st.rot[1],st.rot[2]);group.scale.setScalar(st.scale);if(cfg.fov!=null&&st.restFov!=null){camera.fov=st.fov;camera.updateProjectionMatrix();}};// Hold at the offset during the optional delay.
elapsedRef.current+=dt;if(elapsedRef.current<delay){applyTransform();return;}const omega=6*Math.max(.1,speed);const zeta=cfg.bounce?.6:.85;const targets=[0,0,0,0,0,0,1,st.restFov??st.fov];const values=[st.pos[0],st.pos[1],st.pos[2],st.rot[0],st.rot[1],st.rot[2],st.scale,st.fov];let settled=true;for(let i=0;i<8;i++){// Skip channels this animation doesn't touch (keep them exactly at rest).
const touched=i<3&&cfg.position||i>=3&&i<6&&cfg.rotation||i===6&&cfg.scale!=null||i===7&&cfg.fov!=null;if(!touched){values[i]=targets[i];continue;}const[v,vel]=springStep(values[i],st.vel[i],targets[i],omega,zeta,dt);values[i]=v;st.vel[i]=vel;if(Math.abs(v-targets[i])>SETTLE_EPS||Math.abs(vel)>SETTLE_EPS){settled=false;}}st.pos=[values[0],values[1],values[2]];st.rot=[values[3],values[4],values[5]];st.scale=values[6];st.fov=values[7];applyTransform();if(settled){// Snap exactly to rest and stop doing per-frame work.
group.position.set(0,0,0);group.rotation.set(0,0,0);group.scale.setScalar(1);if(cfg.fov!=null&&st.restFov!=null){camera.fov=st.restFov;camera.updateProjectionMatrix();}doneRef.current=true;}});}/** Wrapper group that hosts the transform enter animation. */export function EnterAnimatedGroup({type,enabled,speed,delay,children}){const ref=useRef(null);useEnterTransform({groupRef:ref,type,enabled,speed,delay});return /*#__PURE__*/_jsx("group",{ref:ref,children:children});}
export const __FramerMetadata__ = {"exports":{"EnterAnimatedGroup":{"type":"reactComponent","name":"EnterAnimatedGroup","slots":["children"],"annotations":{"framerContractVersion":"1"}},"useEnterTransform":{"type":"function","annotations":{"framerContractVersion":"1"}},"EnterAnimationType":{"type":"tsType","annotations":{"framerContractVersion":"1"}},"ENTER_ANIMATION_OPTIONS":{"type":"variable","annotations":{"framerContractVersion":"1"}},"isTransformAnimation":{"type":"function","annotations":{"framerContractVersion":"1"}},"ENTER_ANIMATION_TITLES":{"type":"variable","annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Enter_animations.map