<?php
/**
 * Ten questions and answers per service page, keyed by service slug.
 *
 * Kept out of content.php for the same reason content-web.php and
 * content-software.php are: this is long-form prose that would otherwise bury
 * the service catalogue it sits beside.
 *
 * templates/service-detail.php renders whatever it finds here and emits it as
 * FAQPage structured data. A slug with no entry simply renders no FAQ section,
 * so this file can be filled a service at a time.
 *
 * House rules for an answer here:
 *   - Answer the question asked in the first sentence, then justify it.
 *   - Name the real constraint. "It depends" is only useful with the "on what".
 *   - Where the honest answer is "you may not need this", say so.
 */

declare(strict_types=1);

const SERVICE_FAQS = [

    /* ---- AI Consulting ------------------------------------------------- */
    'ai-consulting' => [
        ['q' => 'How is this different from your Agentic AI Strategy service?',
         'a' => 'Scope. Agentic AI Strategy assumes you already want agents and picks which workflows should get them. AI Consulting sits a level above that: it asks whether AI is the right instrument at all, across your whole organisation, and often concludes that two departments should buy a licence and one should build. If you already know you want an agent, start with the agentic engagement and save yourself a phase.'],
        ['q' => 'What do we actually receive at the end?',
         'a' => 'A written assessment of your data and process readiness, a ranked portfolio of candidate use cases with effort and value attached to each, a build-buy-wait recommendation per candidate, a governance outline covering approvals and data handling, and a phased roadmap. It is written to be read by your board, not only by your engineers.'],
        ['q' => 'How long does it take and what does it cost?',
         'a' => 'Three to five weeks from kick-off to a board-ready plan for a mid-sized organisation, longer if several business units are in scope. It is a fixed-price engagement because the scope is genuinely knowable up front, and the fee is credited against the first build if you go ahead with us.'],
        ['q' => 'We already have an AI strategy deck. Is this redundant?',
         'a' => 'Often, yes, and we will tell you within the first week if so. The deck is usually not the problem — most are directionally right. What they tend to lack is the unglamorous part: whether your data can actually support the use case, what the unit economics look like at full volume, and who owns the outcome when it ships. If your deck covers those, you do not need us for this.'],
        ['q' => 'Who needs to be involved from our side?',
         'a' => 'Someone who owns a P&L, someone who knows where the data actually lives, and one or two people who do the work being considered for automation. That last group matters most and is the one usually left out. They know the exceptions, and the exceptions are what decide whether automation is feasible.'],
        ['q' => 'Will you recommend buying software instead of building?',
         'a' => 'Regularly. If a packaged product models your workflow well, a licence is cheaper than a build and we say so in writing. We make our money on the builds that are genuinely worth building, and recommending one that is not is how a consultancy loses a client in year two.'],
        ['q' => 'How do you assess whether our data is ready?',
         'a' => 'We sample it rather than trust a schema. That means looking at real records for completeness, consistency of coding, how far back reliable history goes, and how much meaning lives in free-text fields nobody has structured. Most readiness failures we find are not missing data — they are the same concept recorded three different ways in three systems.'],
        ['q' => 'Do you cover governance and compliance?',
         'a' => 'Yes, at the level of what you must be able to evidence: approval thresholds, what data may leave your tenancy, retention, and the audit record you will need when a regulator or enterprise customer asks how a decision was made. We are not your lawyers, and for regulated sectors we expect to work alongside your counsel rather than replace them.'],
        ['q' => 'What if the honest answer is that we should do nothing this year?',
         'a' => 'Then that is the recommendation, with the reasoning and the conditions that would change it. It is an uncomfortable report to deliver and it has happened. Spending a consulting fee to find out that a two-crore build would have failed is the cheapest outcome of the engagement, not a wasted one.'],
        ['q' => 'Can you help us hire for this rather than do it for us?',
         'a' => 'Yes. The capability plan covers what to hire, what to train and what to outsource, and we will sit in interviews and score technical exercises if that helps. Building an internal team is the right destination for most organisations; the question is only what to do in the eighteen months it takes to get there.'],
    ],

    /* ---- Generative AI Development ------------------------------------- */
    'gen-ai-development' => [
        ['q' => 'What makes a generative feature worth building?',
         'a' => 'Volume and tolerance. It is worth building where a person currently produces the same kind of output many times a day, and where a draft that needs light editing is still faster than starting from nothing. It is a poor fit where the output must be exactly right the first time and cannot be reviewed — that is a rules engine, not a model.'],
        ['q' => 'How do you stop it inventing things?',
         'a' => 'Three mechanisms, and none of them is a prompt that says "do not hallucinate". Answers are grounded in your own sources and cite them, outputs are validated against a schema before anything downstream accepts them, and the whole thing is scored on a fixed set of your real cases before release. Where a claim cannot be grounded, the design is for the system to say so rather than fill the gap.'],
        ['q' => 'Which model do you use?',
         'a' => 'Whichever wins on your tasks, and we benchmark rather than assume. In practice a large model handles the difficult minority of cases and a small, cheap one handles the bulk, with routing between them. Naming a single model in a proposal is a warning sign: the leaderboard changes every few months and the architecture should not have to.'],
        ['q' => 'What does it cost to run once it is live?',
         'a' => 'It depends on volume and how much context each call carries, which is why we model it before building rather than after. Caching repeated work, compressing prompts and routing cheap tasks to small models routinely cut inference cost by more than half. We will give you a cost per thousand operations, and a ceiling.'],
        ['q' => 'Can it write in our brand voice?',
         'a' => 'To a useful degree. Style is enforced with examples rather than adjectives — showing the model twenty pieces of your own approved copy works far better than describing your tone — plus automated checks for the things you never say. Expect it to produce a good draft in your voice, not to be indistinguishable from your best writer.'],
        ['q' => 'How long until we see something working?',
         'a' => 'Three to six weeks for a first feature in production. A rough demo can exist in days; the gap between the two is the evaluation set, the validation, the failure paths and the cost controls, which is also the gap between something that impresses in a meeting and something you can leave switched on.'],
        ['q' => 'Does our data get used to train anyone else\'s model?',
         'a' => 'No. We run against enterprise endpoints with training disabled, or against open-weight models inside your own infrastructure where residency or contract terms require it. That choice is made before the first line of code, because retrofitting it is a migration.'],
        ['q' => 'What happens when the model provider changes versions?',
         'a' => 'We re-run your evaluation set against the new version, compare it against the current one and cut over only if it holds. Providers deprecate versions with limited notice, and the teams that get hurt are the ones with no test set to measure the change against.'],
        ['q' => 'Can you add this to our existing product rather than building new?',
         'a' => 'Yes, and that is the more common request. The feature ships as a separate service behind a flag so your existing application keeps running untouched and the new path can be switched off in one call. See AI Enablement for Existing Products for that shape of engagement specifically.'],
        ['q' => 'What if the output quality is not good enough?',
         'a' => 'Then we find out during the evaluation phase rather than after launch, and you decide with numbers in front of you. Sometimes the fix is retrieval or prompt work; sometimes the honest answer is that the task needs a human and the model should only be drafting. We would rather narrow the scope than ship something your team stops trusting.'],
    ],

    /* ---- AI Chatbot Development ---------------------------------------- */
    'ai-chatbot-development' => [
        ['q' => 'How is this different from the chatbot our helpdesk already offers?',
         'a' => 'Most bundled bots match keywords against a list of canned replies. This answers from your actual documentation and product data, cites where the answer came from, and can take real actions like checking an order or changing a booking. The difference shows up on the questions nobody wrote a canned reply for, which is most of them.'],
        ['q' => 'What happens when it does not know the answer?',
         'a' => 'It says so and hands over, with the conversation attached so the customer does not repeat themselves. That path is designed first, not added later. A bot that guesses confidently when it is unsure does more damage to trust than one that escalates twice as often.'],
        ['q' => 'What deflection rate should we expect?',
         'a' => 'Sixty percent or better on first-line volume is typical once the content behind it is in reasonable shape, and the content is usually the limiting factor rather than the model. We report the unanswered questions weekly, because that list is the roadmap for both the bot and your documentation.'],
        ['q' => 'Which channels can it run on?',
         'a' => 'Web widget, in-app, WhatsApp Business, and inside your helpdesk as an agent assist. All of them run off one backend, so an answer cannot drift between channels — which is the usual failure when each channel gets its own bot.'],
        ['q' => 'Can it handle Indian languages?',
         'a' => 'Yes, and it answers in the language it was asked in. The source content stays in one place rather than being maintained per language, which is what keeps translations from going stale at different rates. Quality is strongest in English, Hindi and Tamil; we test the specific languages you need before committing.'],
        ['q' => 'Can it do more than answer questions?',
         'a' => 'Yes — order status, booking changes, ticket creation and similar actions, each implemented as an explicit tool with its own permissions rather than as free text the bot improvises. Anything that moves money or changes an entitlement is gated behind confirmation.'],
        ['q' => 'How long does it take to deploy?',
         'a' => 'Three to five weeks to production. The variable is not the bot, it is how your knowledge is stored: clean documentation shortens it, and a decade of answers living in individual agents\' heads lengthens it considerably.'],
        ['q' => 'How do you keep it from being manipulated by users?',
         'a' => 'Untrusted input is treated as data, never as instruction, and the bot\'s tool access is scoped so that even a successful prompt injection cannot reach anything it was not already allowed to touch. The blast radius is bounded by the permissions, not by the model\'s good behaviour.'],
        ['q' => 'What does it cost to run per conversation?',
         'a' => 'Usually a few rupees per conversation at typical lengths, driven by how much context each turn carries. Caching common answers and routing simple turns to a smaller model brings that down substantially, and we give you the per-conversation figure before rollout rather than after the first invoice.'],
        ['q' => 'Who maintains the answers after launch?',
         'a' => 'Your team owns the content; the bot reads it. That is deliberate — the moment answers live somewhere only we can edit, you have a dependency you did not ask for. We provide the review queue and the weekly gap report, and can run maintenance on a retainer if you would rather not.'],
    ],

    /* ---- AI Copilot Development ---------------------------------------- */
    'ai-copilot-development' => [
        ['q' => 'What is the difference between a copilot and a chatbot?',
         'a' => 'Where it lives and who it serves. A chatbot is a destination your customer goes to with a question. A copilot sits inside a screen your own team already works in, sees what they are looking at, and offers help without being asked a question at all. The hard part is context, not conversation.'],
        ['q' => 'Does it act on its own?',
         'a' => 'No, by default it proposes and a person accepts. Anything that writes to a system requires an explicit confirmation rather than an inference. That boundary is the design; if you want a system that acts autonomously, that is agent work and belongs in a different engagement.'],
        ['q' => 'How does it know what the user is looking at?',
         'a' => 'The application passes it the current record, filters and selection as structured context. That is why a copilot is built into a product rather than bolted onto it — the quality of the suggestions is mostly a function of how much context the host screen is willing to hand over.'],
        ['q' => 'Where should it appear in the interface?',
         'a' => 'Side panel, command palette or inline completion, and the right answer depends on how the screen is actually used. Inline suits repetitive entry; a panel suits investigation; a palette suits power users who already know what they want. We prototype the one that fits your workflow rather than the one that demonstrates best.'],
        ['q' => 'How do we know whether it is actually helping?',
         'a' => 'Accept, edit and reject are recorded per suggestion, so you can see the acceptance rate by feature and by user cohort. That is both the quality signal and the training set for the next iteration. A copilot with a low acceptance rate is not a copilot, it is a distraction, and the numbers say which you have.'],
        ['q' => 'What does it cost per user per month?',
         'a' => 'It depends on how often the copilot is invoked and how much context each call carries, so we model it per seat before rollout and set a budget ceiling per user. Rolling an unmetered copilot out to a whole company is the most common way these projects produce a surprising invoice.'],
        ['q' => 'Can it be added to software we did not build?',
         'a' => 'Sometimes. If the product has an API or an extension point, yes. If it is a closed desktop application with neither, the honest answer is usually no, and the alternative is automation around it rather than a copilot inside it.'],
        ['q' => 'How long does it take?',
         'a' => 'Four to eight weeks for a copilot inside an existing product, assuming the host application can supply context without significant refactoring. Where that plumbing does not exist yet, most of the timeline is that work rather than the AI.'],
        ['q' => 'Will it leak data between users or tenants?',
         'a' => 'Not if permissions are enforced at retrieval, which is how we build it: the copilot can only surface what the person using it is already entitled to see. In a multi-tenant product this is the single most important thing to get right, and it is tested explicitly rather than assumed.'],
        ['q' => 'What if our users simply ignore it?',
         'a' => 'That is the most common failure, and it is usually a placement problem rather than a quality one. The fix is to put the suggestion where the decision is actually made rather than in a panel to the side. We instrument usage from day one so this is visible in week two rather than at the end of the quarter.'],
    ],
    /* ---- RAG Development ----------------------------------------------- */
    'rag-development' => [
        ['q' => 'Our first RAG attempt gave vague answers. What usually causes that?',
         'a' => 'Retrieval, nine times out of ten. The model was never shown the right passage, so it answered from general knowledge and sounded plausible. Before touching prompts we measure recall on a labelled question set — if the correct passage is not in the top results, no amount of prompt engineering fixes it.'],
        ['q' => 'Why not just put everything in the prompt now that context windows are huge?',
         'a' => 'Cost and precision. A large context costs on every single call and dilutes attention across irrelevant material, which measurably lowers answer quality on specific questions. Long context is genuinely useful for reasoning over one big document; it is a poor substitute for retrieval across ten thousand of them.'],
        ['q' => 'What kinds of documents can you ingest?',
         'a' => 'PDFs including scanned ones, Word and Excel files, wiki and Confluence pages, ticket history, email archives and database records. Scanned and inconsistently formatted paperwork is the part that takes real work — that is where most of the ingestion effort goes, not in the embedding.'],
        ['q' => 'How do you handle documents that contradict each other?',
         'a' => 'By dating and ranking sources rather than pretending the conflict is not there. The system prefers the most recent authoritative version, shows which document each claim came from, and where two current sources genuinely disagree it says so instead of silently picking one. Surfacing the contradiction is usually more valuable than resolving it.'],
        ['q' => 'What happens when we withdraw or update a policy?',
         'a' => 'Re-indexing runs on change, and deletions propagate. This matters more than it sounds: an assistant confidently quoting a policy you retired last quarter is worse than one that says it does not know, because nobody checks an answer that sounds right.'],
        ['q' => 'Can it respect who is allowed to see what?',
         'a' => 'Yes, and permissions are enforced at retrieval rather than filtered from the answer afterwards. The distinction matters — a system that retrieves a restricted document and then tries not to mention it has already leaked it into the model context.'],
        ['q' => 'How do you measure whether it is any good?',
         'a' => 'Two separate scores. Retrieval recall asks whether the right passage was fetched; answer quality asks what the model did with it. Measuring only the second leaves you unable to tell a retrieval failure from a generation failure, which is why so many RAG projects stall at "it is sometimes wrong".'],
        ['q' => 'How long does a first version take?',
         'a' => 'Three to six weeks to production for a defined corpus. Clean, well-structured documentation lands at the shorter end; a decade of scanned PDFs with inconsistent layouts lands at the longer one, and occasionally needs an OCR phase of its own first.'],
        ['q' => 'Do we need a dedicated vector database?',
         'a' => 'Usually not at first. pgvector inside the PostgreSQL you already run handles corpora well into the millions of chunks and saves you an entire piece of infrastructure to operate. We move to a dedicated store when scale or latency genuinely demands it, which is later than most vendors suggest.'],
        ['q' => 'Can this run entirely inside our own infrastructure?',
         'a' => 'Yes. Open-weight models with local embedding and inference, so no document text leaves your environment. It costs more in engineering and hardware than a hosted API, and for regulated or contractually restricted data it is frequently the only acceptable answer.'],
    ],

    /* ---- Computer Vision Development ------------------------------------ */
    'computer-vision-development' => [
        ['q' => 'How many images do you need to get started?',
         'a' => 'Fewer than people expect for a narrow task — a few hundred well-chosen examples per class often gets a useful first model. What matters far more than volume is coverage: images from your actual cameras, your actual lighting, and crucially your actual failure cases. A thousand clean images and no bad ones produces a model that fails the first time something is dirty.'],
        ['q' => 'Why do vision projects fail more often than other AI work?',
         'a' => 'Because they are usually validated on tidy sample images and deployed against a smeared lens in poor light at an angle nobody anticipated. The model is rarely the problem. We insist on collecting from the real environment before promising accuracy, which occasionally means the honest first deliverable is a camera and lighting recommendation.'],
        ['q' => 'What accuracy can we expect?',
         'a' => 'For a well-scoped detection or classification task on decent imagery, above ninety-five percent is a reasonable target. But the useful question is which error you can least afford: a system that never misses a defect but flags extra ones is very different from the reverse, and we tune to whichever costs you more.'],
        ['q' => 'Does the video have to leave our site?',
         'a' => 'No. Inference can run on the edge, next to the camera, which keeps footage on your premises and means a network outage does not stop the line. That is the usual choice for factory and field deployments, and often the only one acceptable where people are in frame.'],
        ['q' => 'Can it read our paperwork as well as inspect products?',
         'a' => 'Yes — printed and handwritten forms, invoices, IDs and delivery notes. Document vision is a different pipeline from scene inspection but the same engagement. It is particularly worth it where a template-based OCR tool has already been tried and defeated by inconsistent layouts.'],
        ['q' => 'What hardware do we need?',
         'a' => 'Less than you would think for most tasks. A small edge device per camera handles typical detection workloads; a GPU server is only warranted for high frame rates, many streams, or heavy models. We size this after the pilot rather than quoting hardware before knowing the workload.'],
        ['q' => 'How does it handle a product or packaging change?',
         'a' => 'It needs new examples, and the system is built expecting that. Low-confidence frames route to a person for review, and their corrections feed the next training round, so a change degrades performance temporarily rather than breaking the system. Without that loop a vision model quietly decays and nobody notices until yield drops.'],
        ['q' => 'How long from pilot to production line?',
         'a' => 'Six to twelve weeks typically, and the data collection phase is usually the longest part rather than the modelling. Running the model in shadow alongside existing inspection for a couple of weeks before it makes decisions is part of that, not an optional extra.'],
        ['q' => 'Can it work with the cameras we already have?',
         'a' => 'Often, yes, and we always check before proposing new ones. Existing CCTV is frequently adequate for counting and presence detection but not for fine defect inspection, where resolution and lighting matter more than the model does. We will tell you which category you are in early.'],
        ['q' => 'What about people appearing in the footage?',
         'a' => 'That needs deciding explicitly before deployment, not after. Depending on the use case we blur or discard frames containing people, process on-site so footage never leaves, and set retention deliberately. Where the purpose genuinely involves people, that is a consent and policy question for you with your counsel, and we build to whatever that decides.'],
    ],

    /* ---- RPA Development ------------------------------------------------ */
    'rpa-development' => [
        ['q' => 'Is RPA not obsolete now that everything has an API?',
         'a' => 'Everything does not have an API. Plenty of the systems that run Indian enterprises — older ERPs, government portals, bank interfaces, industry-specific desktop software — expose nothing usable, and the vendor has no roadmap to change that. RPA is the bridge for exactly those, and it is far cheaper than the migration that would otherwise be required.'],
        ['q' => 'Robots break every time a screen changes. How is yours different?',
         'a' => 'Because it is engineered rather than recorded. Recorders capture screen coordinates and shatter on the first layout change; we drive stable element identifiers, handle waits explicitly, and define what happens on every failure. A robot still needs maintenance when a vendor redesigns a page, but it is a fix rather than a rebuild.'],
        ['q' => 'What kind of tasks are worth automating this way?',
         'a' => 'High-volume, rule-governed, low-judgement work: rekeying between systems, downloading and filing reports, reconciling two lists, submitting the same form repeatedly. If a task needs judgement on most items rather than a few, RPA is the wrong tool and an agent or a person is the right one.'],
        ['q' => 'What is the difference between attended and unattended robots?',
         'a' => 'An attended robot runs on someone\'s desktop and assists them with a step while they work; an unattended one runs on a server against a queue with nobody watching. They need different controls — unattended work needs stronger exception handling, because there is no human present to notice something has gone strange.'],
        ['q' => 'What happens when the robot hits something unexpected?',
         'a' => 'It does one of three defined things: retry, park the item for human review, or stop. Never a fourth, and never silently skip. A robot that quietly passes over records it could not handle is worse than no robot, because the gap is invisible until someone audits.'],
        ['q' => 'Can a robot handle a step that needs judgement?',
         'a' => 'That is where we combine the two: a model reads the scanned form or decides the category, and the robot does the navigating and typing. This is most of what we build now, and it widens the range of automatable work considerably compared with rules alone.'],
        ['q' => 'How quickly does it pay for itself?',
         'a' => 'For a genuinely repetitive task with meaningful volume, usually within a few months. We size that before building by timing the current process — if the honest sum does not clear the build cost inside a year, we say so rather than proceeding.'],
        ['q' => 'Do we need to buy UiPath or Power Automate licences?',
         'a' => 'Not necessarily. Those platforms earn their licence cost when you are running a large robot estate that needs central orchestration and governance. For a handful of processes, Python with Playwright does the same work with no per-robot fee. We will recommend the licence when it is genuinely cheaper.'],
        ['q' => 'Is it secure to give a robot our system credentials?',
         'a' => 'It is, provided the robot gets its own identity rather than borrowing a person\'s. Each robot has credentials scoped to exactly what it needs, stored in a managed secret store, with every action logged against the record it touched. Sharing an employee\'s login with a robot is the practice to avoid, and it is unfortunately common.'],
        ['q' => 'How long does the first robot take?',
         'a' => 'Two to six weeks. The build is rarely the long part — documenting how the task is actually performed, including the exceptions people handle without realising they are exceptions, usually takes longer than automating it.'],
    ],

    /* ---- Agentic AI Strategy & Consulting -------------------------------- */
    'agentic-ai-strategy' => [
        ['q' => 'How do we know whether we are ready for agents at all?',
         'a' => 'Three tests. Are the rules of the workflow written down somewhere other than in people\'s heads? Are the actions reversible if the agent gets one wrong? Can you measure today what good looks like? A no to any of those is not a blocker, but it tells you what phase one actually has to be, and it is usually not the agent.'],
        ['q' => 'Which workflow should we automate first?',
         'a' => 'Rarely the one that demonstrates best. We score candidates on volume, handling time, error rate, how reversible the actions are, and how much context lives only in one person\'s head. The winner is usually unglamorous — a queue nobody enjoys — and that is exactly why it works.'],
        ['q' => 'What does the engagement produce?',
         'a' => 'A measured audit of the workflows considered, an autonomy score for each, a build-buy-leave-alone recommendation, the target agent architecture, and a phased roadmap where each phase is gated on the previous one\'s numbers. Everything carries the assumptions it rests on so you can argue with them.'],
        ['q' => 'How long does it take?',
         'a' => 'Two to three weeks from audit to written roadmap for three to five workflows. Longer if the processes are undocumented, because then the first task is establishing what actually happens rather than what the process document claims happens.'],
        ['q' => 'Will you tell us not to build something?',
         'a' => 'Yes, and it is a normal outcome. The most common "do not build" is a workflow whose rules turn out to be contested between two departments — no agent resolves a disagreement about policy, it just automates whichever version it was told. That needs settling first, by people.'],
        ['q' => 'How is this different from general AI consulting?',
         'a' => 'This one assumes agents are on the table and focuses on which work they should take. Our AI Consulting service sits above it and asks whether AI is the right instrument at all across the organisation. If you already know you want agents, start here; if that is still an open question, start there.'],
        ['q' => 'What should we expect to spend on the build afterwards?',
         'a' => 'The roadmap carries a band per phase rather than a single figure, because the count of integrations moves the number more than anything else. A first agent against one or two systems is a different order of cost from one that has to touch nine, and you will see which you are looking at before committing.'],
        ['q' => 'Do you need access to our systems for the audit?',
         'a' => 'Read access to the relevant systems helps considerably, but we can work from exports and interviews where access takes time to arrange. What we do need is time with the people who do the work — an audit built only from management\'s description of a process consistently misses the exceptions.'],
        ['q' => 'Can we do this ourselves?',
         'a' => 'You can, and some clients should. What an outside team brings is scar tissue from other deployments and no stake in any particular department\'s preferred answer. If you have someone internal who can measure processes honestly and is empowered to conclude "do not build", that is genuinely as good.'],
        ['q' => 'What if we already started building and it stalled?',
         'a' => 'That is a common starting point and the audit changes shape accordingly: we look at what was built, why it stalled, and whether the problem was the workflow chosen, the data, or the engineering. Most stalled agent projects we see picked a workflow whose rules were never actually written down.'],
    ],
    /* ---- Custom AI Agent Development ------------------------------------ */
    'custom-agent-development' => [
        ['q' => 'When is a custom agent worth it over a ready-made one?',
         'a' => 'When the work is specific to how you compete. If the task is support triage or invoice extraction, an archetype from our AI Agent Solutions catalogue does it in days for a fraction of the cost. Build custom when the workflow encodes something proprietary, when the rules are yours alone, or when an archetype has been tried and hit a wall.'],
        ['q' => 'What actually takes the time in building one?',
         'a' => 'Not the model. It is the tools the agent may call, the schema it must return, the permissions on each action, the failure paths, and the evaluation set. The prompt is usually a day\'s work and gets rewritten a dozen times; the plumbing around it is what makes the difference between a demo and something you leave running.'],
        ['q' => 'How do you stop an agent doing something damaging?',
         'a' => 'By bounding what it can reach rather than trusting it to behave. Every capability is an explicit, typed tool with its own permissions, anything above a threshold you set routes to a human queue, and there is one switch that halts it mid-run. An agent that can call anything is an agent nobody can reason about.'],
        ['q' => 'What about prompt injection from documents it reads?',
         'a' => 'Untrusted content is treated as data, never as instruction — the same rule we hold ourselves to. Beyond that, the agent\'s tool access is scoped so a successful injection cannot reach anything it was not already permitted to touch. You bound the blast radius rather than hoping the model resists.'],
        ['q' => 'How do you know it is working well enough to ship?',
         'a' => 'A golden set drawn from your real cases, scored on every prompt and model change. A release that regresses does not ship. Without that set you are shipping on vibes, which is fine for a demo and indefensible for anything touching a customer or a ledger.'],
        ['q' => 'How long does the first agent take?',
         'a' => 'Four to eight weeks to production. The variable is integration count more than agent complexity — an agent that reads one system and writes to another is quick; one that has to reconcile across six is a different project, and we will say which yours is before starting.'],
        ['q' => 'Can it work with our existing systems?',
         'a' => 'Yes, and that is most of the work. ERPs, CRMs, ticketing, databases, and systems with no API at all via file or UI-level automation. See Agentic AI Integration for that layer specifically — on a single-agent build it is included rather than separate.'],
        ['q' => 'What does it cost to run per task?',
         'a' => 'Usually cents rather than rupees per completed task, but it depends heavily on how many steps and how much context each run carries. We model it during the build and set a per-run token and cost ceiling, because an agent that loops is an agent that spends.'],
        ['q' => 'What happens when the underlying model changes?',
         'a' => 'We re-run your evaluation set against the new version and cut over only if it holds. Providers deprecate versions with limited notice; the teams that get hurt are the ones with nothing to measure the change against. This is what Agent Operations covers after launch.'],
        ['q' => 'Who owns the agent when the project ends?',
         'a' => 'You do — repository, prompts, evaluation set, infrastructure, all in your accounts from the first week. Your engineers pair with ours through the build and hold the runbook at the end. A permanent dependency on us is not the goal and never has been.'],
    ],

    /* ---- AI Agent Solutions --------------------------------------------- */
    'ai-agent-solutions' => [
        ['q' => 'What exactly am I getting — software or a service?',
         'a' => 'A proven agent archetype, configured against your systems and your data, and then run. The design work is already done: the tools, the prompts and the evaluation set exist. What you pay for is connection, configuration and operation rather than invention.'],
        ['q' => 'Which archetypes do you have?',
         'a' => 'The jobs most businesses share — support triage, sales follow-up, document extraction, reconciliation, reporting and scheduling. If your need is not on that list, it is a custom build rather than an archetype, and we will say so rather than forcing a poor fit.'],
        ['q' => 'How is this cheaper than a custom agent if it still needs configuring?',
         'a' => 'Because the expensive part is already built and tested. A custom agent is four to eight weeks of design, tooling and evaluation; an archetype is three to seven days of pointing an existing one at your systems. You are sharing the cost of the engineering with everyone else who uses that archetype.'],
        ['q' => 'Is it actually tailored, or is it generic?',
         'a' => 'It is configured against your data, your terminology and your approval thresholds before it answers anyone. What it is not is redesigned — the workflow shape is fixed. If your process differs from the archetype in a way that matters, that difference is the argument for a custom build.'],
        ['q' => 'Does it have the same safety controls as a custom build?',
         'a' => 'Identical. Typed tools, scoped permissions, schema validation, full action trail, human approval gates. Faster to deploy does not mean looser — the controls are part of the archetype rather than something added per client.'],
        ['q' => 'How do we know it is right before letting it act?',
         'a' => 'Shadow mode. It runs alongside your team without acting and its decisions are compared with theirs until the numbers justify letting it act. Usually a couple of weeks. It is also the cheapest way to discover that your process differs from what the process document says.'],
        ['q' => 'What if we outgrow it?',
         'a' => 'It becomes the specification for a custom agent rather than something thrown away. By then you have months of real cases, a measured accuracy baseline and a clear list of what it could not handle — which is a far better brief than anything you could have written at the start.'],
        ['q' => 'How is this different from buying an off-the-shelf AI product?',
         'a' => 'A product runs on the vendor\'s infrastructure with your data inside it and changes when their roadmap says so. This runs in your environment, against your systems, with the configuration and the trail in your hands. Where a packaged product genuinely fits, we will tell you to buy it.'],
        ['q' => 'What does it cost?',
         'a' => 'A setup fee for configuration and integration, then a monthly run cost that scales with volume. It is materially less than a custom build for the same job, and we will show you both numbers rather than only the one we would rather sell.'],
        ['q' => 'Can we run several archetypes at once?',
         'a' => 'Yes, and it is common — support triage and document extraction often go in together. Once more than two or three are running and need to hand work between them, that is orchestration, and Multi-Agent Orchestration is the engagement that covers it properly.'],
    ],

    /* ---- Multi-Agent Orchestration --------------------------------------- */
    'multi-agent-orchestration' => [
        ['q' => 'Do we actually need multiple agents?',
         'a' => 'Usually not, and that is the honest starting answer. Multi-agent is worth its extra machinery only when a process genuinely has separable roles needing different skills or different permissions. If one agent with more tools would do, build that — a crowd of agents is harder to debug and rarely better.'],
        ['q' => 'What makes orchestration hard?',
         'a' => 'Not the conversation between agents. It is the state: which agent currently holds the task, what happens when one fails halfway, how you stop two of them handing work back and forth, and how you tell afterwards which one got it wrong. Those are distributed systems problems wearing an AI hat.'],
        ['q' => 'How do you stop them looping and burning budget?',
         'a' => 'Step ceilings, cost ceilings and cycle detection, enforced by the supervisor rather than requested in a prompt. Every run has a maximum number of steps and a maximum spend, and hitting either stops the run and parks it for review.'],
        ['q' => 'Can we stop the whole thing mid-run?',
         'a' => 'Yes — one switch halts the squad, and every autonomous action has a defined reversal. We treat that as a requirement rather than a feature. Autonomy you cannot stop is not autonomy, it is exposure.'],
        ['q' => 'How do you debug something non-deterministic?',
         'a' => 'By making every run replayable. Each step, input and tool call is recorded so a run can be walked through afterwards exactly as it happened. Without that, debugging a multi-agent system is guesswork, and it is the single thing most teams skip and later regret.'],
        ['q' => 'How do you know which agent caused a bad outcome?',
         'a' => 'Each role is scored on its own cases as well as on the end-to-end result. That separation means a regression can be attributed rather than argued about — otherwise a drop in overall quality sends the whole team hunting across every agent at once.'],
        ['q' => 'Should agents share memory?',
         'a' => 'Only deliberately. What the squad knows in common, what stays private to one role and what expires are decided explicitly at design time. Leaked context between agents is a common cause of runs that go subtly strange, because a role starts acting on information it was never meant to weigh.'],
        ['q' => 'How long does it take to build?',
         'a' => 'Six to twelve weeks for an orchestrated squad in production, assuming the individual agent capabilities are understood. If you are designing the agents and the orchestration simultaneously, expect longer — and we would usually advise getting one agent working properly first.'],
        ['q' => 'Which framework do you use?',
         'a' => 'LangGraph for the state machine, with Temporal where a workflow needs to survive process restarts and run for days. The framework matters less than having an explicit state machine at all; the failure mode we are avoiding is agents coordinating implicitly through conversation.'],
        ['q' => 'What does a realistic first phase look like?',
         'a' => 'Two or three agents on one process, with a supervisor and a human at the exception queue. Not a dozen agents across a department. The number of ways a multi-agent system can go wrong grows faster than the number of agents, so the first phase should be small enough to understand completely.'],
    ],

    /* ---- Agentic AI Integration ------------------------------------------ */
    'agentic-ai-integration' => [
        ['q' => 'What does this cover that a normal API integration does not?',
         'a' => 'The parts that only matter when a non-deterministic actor is calling. Retries that cannot duplicate a payment, permissions scoped per agent rather than shared, approval gates above a threshold, and an action trail detailed enough to reconstruct a decision. A conventional integration assumes the caller is predictable code.'],
        ['q' => 'Which systems can you connect to?',
         'a' => 'SAP, Dynamics, Salesforce, Zoho, Tally, NetSuite, Jira, Zendesk and in-house databases, plus anything with a documented API. Systems with no API are reached by file, database or UI-level automation and wrapped so nothing downstream has to know the difference.'],
        ['q' => 'What if our ERP has no usable API?',
         'a' => 'Then we use whatever it does expose — scheduled file drops, a database view, or UI automation — and put a proper contract layer in front of it. That layer is the point: when the vendor eventually ships an API, you swap the adapter and nothing above it changes.'],
        ['q' => 'How do you stop a retry creating a duplicate invoice?',
         'a' => 'Every write is idempotent and carries a correlation id, so repeating it is safe by construction. This is the single most common way agent integrations cause real damage — a timeout that looks like a failure, retried, becoming two payments — and it is prevented at the integration layer rather than in the agent.'],
        ['q' => 'What permissions does the agent get?',
         'a' => 'Its own service identity, scoped to exactly the records it needs. Never a shared admin key. The difference shows up during an incident: scoped credentials make it a contained problem, a shared key makes it an estate-wide one.'],
        ['q' => 'Can we require approval before certain actions?',
         'a' => 'Yes, and the threshold is yours to set — by value, by record type, by customer, or by confidence. Those actions route to a queue with the agent\'s reasoning attached and wait. The gate is built into the integration rather than being a setting someone can switch off.'],
        ['q' => 'How do we audit what the agent did?',
         'a' => 'Every tool call is recorded against the record it touched, with inputs, outputs and the run it belonged to. An auditor can reconstruct a decision without reading a model log, which is the form the question actually arrives in.'],
        ['q' => 'How is this different from your AI Integration Services?',
         'a' => 'This gives agents permissioned reach into your systems. AI Integration Services is the platform layer underneath — model serving, gateways, data pipelines, cost attribution — that serves models to the whole enterprise estate. Many clients need both; they are separable and we will say which you need first.'],
        ['q' => 'Will it slow our systems down?',
         'a' => 'It should not, and we design to avoid it: rate limits per connector, caching for reads that repeat, and queueing for writes so a burst of agent activity does not arrive at your ERP all at once. Agents can generate load in patterns no human user ever would.'],
        ['q' => 'How long does an integration take?',
         'a' => 'A well-documented API is days. A legacy system needing UI automation, sandbox access and a negotiated test window is weeks, and the delay is usually access rather than engineering. We scope integrations individually because the spread is that wide.'],
    ],
    /* ---- AI Integration Services ----------------------------------------- */
    'ai-integration' => [
        ['q' => 'How is this different from AI Enablement and Agentic AI Integration?',
         'a' => 'Three layers of the same stack. AI Enablement adds intelligence to your own product. Agentic AI Integration gives agents permissioned reach into systems. This is the platform underneath both — serving models reliably to the whole enterprise, with one route in and one bill to read. Smaller organisations often need only one of the three.'],
        ['q' => 'Why route every AI call through a gateway?',
         'a' => 'Because otherwise nobody can answer basic questions. Which team is spending what, which model version is in production where, who has a key, and what happens when a provider has an outage. One route gives you quotas, logging and cost attribution per department without each team building it separately.'],
        ['q' => 'What happens when the model provider goes down?',
         'a' => 'The gateway fails over to a secondary provider or a smaller local model, depending on what you have configured for that route. The goal is that an outage degrades a feature rather than taking down an application. Without that layer, every integration inherits the provider\'s availability directly.'],
        ['q' => 'Can we run models on our own infrastructure?',
         'a' => 'Yes — open-weight models served with vLLM inside your environment, which is the usual answer where data residency, contract terms, or cost at very high volume rule out a public API. It costs more in engineering and hardware, and below a certain volume a hosted API is genuinely cheaper. We model both before recommending.'],
        ['q' => 'How do we stop AI spend getting out of hand?',
         'a' => 'Per-team keys with quotas, budgets enforced at the gateway rather than reviewed monthly, and cost attribution by department and feature. The common failure is not one expensive feature — it is twenty teams each making calls nobody is tracking until the invoice arrives.'],
        ['q' => 'What about the data pipelines?',
         'a' => 'Extraction, cleaning and embedding of the operational records that models need, running on a schedule rather than as a one-off load. Most "the AI does not know about that" complaints are a stale pipeline rather than a model limitation.'],
        ['q' => 'How long does the first integration take?',
         'a' => 'Four to eight weeks to production for the gateway plus one real integration. Subsequent integrations are much faster because the platform work is done — that is the main argument for building this layer before you have six teams each solving it separately.'],
        ['q' => 'Do we need this if we only have one AI feature?',
         'a' => 'No, and we will say so. With one feature, the gateway is overhead. It starts paying when you have several teams making calls, when you need to switch providers without touching application code, or when finance asks which department is spending what.'],
        ['q' => 'Can you work with our existing cloud and CI setup?',
         'a' => 'Yes — AWS, Azure or GCP, deployed through whatever pipeline you already run. We would rather fit your existing operational model than introduce a parallel one your team has to learn and then maintain alongside everything else.'],
        ['q' => 'Who operates it afterwards?',
         'a' => 'Your platform team, with runbooks and dashboards handed over, or us on a retainer if you would rather. It is deliberately boring infrastructure — the whole point is that it stops being interesting once it works.'],
    ],

    /* ---- Autonomous Workflow Automation ----------------------------------- */
    'autonomous-workflow-automation' => [
        ['q' => 'What is the difference between automating a task and a workflow?',
         'a' => 'A task saves minutes; a workflow removes a queue. The test is whether a case can go from arrival to resolution without a person re-entering it somewhere in the middle. Most automation projects stop at tasks and wonder why the headcount never changed.'],
        ['q' => 'What kinds of workflows suit this?',
         'a' => 'High-volume ones with written rules and reversible actions — claims intake, order exceptions, invoice matching, onboarding paperwork, refund processing. Work requiring judgement on most cases rather than a minority is a poor fit, and we would rather tell you that during the audit.'],
        ['q' => 'What happens to the cases the system cannot handle?',
         'a' => 'They route to a person with the system\'s working shown — what it read, what it concluded, why it was unsure. The measure of a good workflow is how few reach that queue, not that none do. A design promising zero exceptions is a design that will handle some cases wrongly instead.'],
        ['q' => 'How do we trust it before letting it act?',
         'a' => 'Shadow mode, usually for a fortnight. It runs alongside your team without acting and its decisions are compared with theirs. You get an agreement rate before anything is live, and it reliably surfaces places where two of your own people would have decided differently.'],
        ['q' => 'How much manual effort does this actually remove?',
         'a' => 'Forty percent or more of handling time is typical on a well-chosen workflow, and we measure the before honestly so the after means something. Beware anyone quoting ninety percent: that number usually counts only the happy path and ignores the exception queue entirely.'],
        ['q' => 'Where do the decision rules live?',
         'a' => 'In version control alongside the workflow, so changing how cases are decided is a reviewable commit rather than a prompt someone edited on a Friday. For anything touching money or entitlement, being able to say exactly what the rule was on a given date matters more than convenience.'],
        ['q' => 'Can it handle documents and email as inputs?',
         'a' => 'Yes — email, forms, tickets and documents including scans. Document intake is usually where template-based tools have already failed, because real paperwork does not keep its layout. That extraction step is part of the workflow rather than a separate project.'],
        ['q' => 'What does it report?',
         'a' => 'Cases handled, deflection rate, exception rate and cost per case, weekly, whether or not the figures flatter us. If the exception rate climbs, something upstream changed and you want to know in week two rather than at quarter end.'],
        ['q' => 'How long to get one live?',
         'a' => 'Eight to fourteen weeks for a first workflow end to end, of which two are usually shadow mode. Faster if the process is genuinely documented; slower where the rules live in the heads of two experienced people, which is the more common case.'],
        ['q' => 'What happens to the people currently doing this work?',
         'a' => 'That is your decision and it deserves an honest answer rather than a slogan. In the deployments we have run, the exception queue still needs experienced people and the volume that was being deferred usually gets picked up. But if the plan is headcount reduction, say so at the start — it changes which workflow you should choose and how much accuracy you need before going live.'],
    ],

    /* ---- Agent Operations, Training & Support ------------------------------ */
    'agent-operations-support' => [
        ['q' => 'Why does a deployed agent need ongoing work at all?',
         'a' => 'Because it is a running system, not a delivery. Model versions change under you, your policies and documents change around it, and the mix of cases arriving drifts. An agent left alone does not stay still — it quietly gets less accurate while continuing to sound exactly as confident.'],
        ['q' => 'How would we notice accuracy dropping?',
         'a' => 'Without monitoring, usually from a customer. With it, from the weekly re-run of the golden set, plus live tracking of refusal rates, tool-call failures and schema violations. The whole point is that we see it before your users do.'],
        ['q' => 'What exactly do you monitor?',
         'a' => 'Accuracy against a fixed case set, latency, cost per run, tool-call failure rates, output schema violations, escalation rate and refusal rate. Alerts are tuned to page a person only when a person is needed — an alert channel everyone mutes is worse than none.'],
        ['q' => 'What happens when a provider deprecates a model?',
         'a' => 'We re-evaluate, re-tune and cut over against the same test set, so the change is measured rather than hoped through. Notice periods are short and getting shorter; this is the single most common cause of a working agent breaking without anyone touching its code.'],
        ['q' => 'Can you take over an agent someone else built?',
         'a' => 'Yes, starting with a paid audit — architecture, prompts, tool permissions, whether an evaluation set exists, and what the failure paths do. Taking over an agent without that audit is how a support engagement turns into an unplanned rebuild.'],
        ['q' => 'What is the response time if something breaks?',
         'a' => 'Set by the SLA you choose, and we would rather agree a realistic one than an impressive one. What is constant is the mechanism: a defined stop, a defined rollback, and a written post-incident note explaining what happened and what changed as a result.'],
        ['q' => 'How often does the knowledge base need refreshing?',
         'a' => 'On change, not on a calendar. Re-indexing runs when documents change, including deletions — an agent quoting a policy you withdrew last quarter is the failure mode that damages trust fastest, because the answer sounds right.'],
        ['q' => 'What does this cost?',
         'a' => 'A monthly retainer scaled to the number of agents and the SLA, plus inference. It is materially less than the cost of an agent silently degrading for a quarter, which is the alternative we are usually being compared against.'],
        ['q' => 'Can our own team learn to do this?',
         'a' => 'Yes, and most should. We pair with your engineers through the engagement and hand over runbooks, dashboards and the evaluation set. A number of clients run their own operations after six months and keep us for model migrations only.'],
        ['q' => 'What if we want to stop using agents altogether?',
         'a' => 'Then the rollback plan gets used and the workflow returns to the manual path, which is why we insist every autonomous action has a defined reversal. It has happened once, for a process whose rules changed faster than the agent could be retrained. Better to unwind cleanly than defend a decision that stopped making sense.'],
    ],

    /* ---- Hire Agentic AI Developers ---------------------------------------- */
    'hire-agentic-ai-developers' => [
        ['q' => 'How is this different from a normal contract developer?',
         'a' => 'Specialisation and habits. These are the same engineers who build our own agent work, so they bring retrieval, orchestration, evaluation and inference-cost experience with them. The evaluation discipline in particular tends to be the thing an otherwise strong generalist has never had to build.'],
        ['q' => 'Do we get named people or a rotating pool?',
         'a' => 'Named people, with names and history you can see before committing. If someone has to change, you agree it beforehand. A pool arrangement is cheaper for the vendor and worse for you, because context is most of the value after the first month.'],
        ['q' => 'Whose process do they work in?',
         'a' => 'Yours. Your repository, your tracker, your review process, your stand-up. Nothing routes through a separate account or a parallel board. If you want a delivery team that runs its own process and reports outwards, that is our Dedicated Engineering Team engagement instead.'],
        ['q' => 'How quickly can someone start?',
         'a' => 'One to two weeks from brief to starting, subject to who is free. We would rather tell you three weeks for the right person than put someone on next Monday who has never built a retrieval pipeline.'],
        ['q' => 'What is the minimum commitment?',
         'a' => 'Monthly, and resizable monthly. A team you cannot resize is a hire with extra steps and none of the benefits. Most engagements run three to nine months and step down as your own team picks the work up.'],
        ['q' => 'Do they only do agent work?',
         'a' => 'Mostly, but not exclusively — real agent work involves plenty of ordinary backend engineering, and they do that too. What they are not is general full-stack cover; if you need someone to build screens for six months, a different arrangement is better value.'],
        ['q' => 'How do we know they are any good before committing?',
         'a' => 'A paid two-week trial on a real piece of your backlog, which we recommend and most clients take. It tells you more than any interview, and it is the same thing we would want in your position.'],
        ['q' => 'Will we become dependent on them?',
         'a' => 'That is the risk in any staffing arrangement and we design against it: pairing with your engineers throughout, written handover as they go, and an explicit expectation that you will eventually run this without us. If an engagement is not reducing your dependence over time, it is not working.'],
        ['q' => 'Who owns what they build?',
         'a' => 'You do, entirely — it is in your repository from the first commit. There is no library or framework of ours that you end up licensed to rather than owning.'],
        ['q' => 'What if we need a whole team rather than one or two people?',
         'a' => 'Then it is our Dedicated Engineering Team engagement, which adds a lead, QA and its own delivery rhythm. The line is roughly four people: below that, embedding individuals into your team works better; above it, the squad needs someone running it.'],
    ],
];
