<?php
/**
 * Ten questions and answers per case study, keyed by study slug.
 *
 * templates/case-study-detail.php renders whatever it finds here and emits it
 * as FAQPage structured data. A slug with no entry simply renders no FAQ
 * section, so this file can be filled a study at a time.
 *
 * A case study is read by someone deciding whether their problem is this
 * problem. The narrative answers what we built; it never answers what it cost,
 * how long it took, what broke, what we would do differently, or whether it
 * would work at their size. Those are the questions here.
 *
 * House rules, the same ones content-service-faqs.php uses:
 *   - Answer the question asked in the first sentence, then justify it.
 *   - Name the real constraint. "It depends" is only useful with the "on what".
 *   - Where the honest answer is "you may not need this", say so.
 *   - No invented figures. Where a number is not ours to publish, say that.
 */

declare(strict_types=1);

const CASE_FAQS = [

    /* ---- Tada — AI ride-hailing ----------------------------------------- */
    'tada-taxi-app' => [
        ['q' => 'What was actually causing the long rider wait times?',
         'a' => 'Dispatch was assigning the nearest driver by straight-line distance, which is the wrong measure in a city. The nearest driver across a river or on the far side of a divided road is not the fastest driver. Routing the decision through real road-network travel time rather than geographic distance is where most of the improvement came from, before any prediction was involved.'],
        ['q' => 'How does the surge prediction differ from ordinary surge pricing?',
         'a' => 'It moves supply before the shortage instead of raising prices after it. The model forecasts demand per zone on a short horizon from historical patterns, weather and local events, and nudges drivers toward zones that are about to get busy. Reactive surge punishes riders for a supply failure; anticipating it is the version worth building.'],
        ['q' => 'Why PostGIS rather than a geospatial service?',
         'a' => 'Because the geo queries and the business data need to be in the same transaction. Matching a rider to a driver touches location, driver state, pricing and trip records at once, and splitting that across a database and an external geo service turns one atomic decision into a distributed one with a race condition in it.'],
        ['q' => 'How do you handle drivers going offline mid-trip?',
         'a' => 'Connection state and trip state are kept separate on purpose. A driver losing signal in a basement car park has not abandoned the trip, so the system holds the assignment, buffers position updates and reconciles when they reconnect. Only a genuine timeout with no movement escalates to reassignment, with a human in the loop.'],
        ['q' => 'How long did this take to build?',
         'a' => 'A ride-hailing platform of this shape is a multi-month build rather than a sprint, and the dispatch engine is a small fraction of it. Payments, driver onboarding and verification, cancellation and refund rules, and the support tooling for when a trip goes wrong take longer than the matching algorithm every time.'],
        ['q' => 'What was the hardest part?',
         'a' => 'Cancellation and edge-case handling, not the AI. Deciding who pays when a driver waits eleven minutes and the rider does not appear is a policy question with a revenue consequence, and it has to be encoded consistently across the app, the driver app, the billing system and the support desk. Getting those four to agree is the real work.'],
        ['q' => 'Would this work for a fleet of thirty vehicles?',
         'a' => 'The dispatch logic would; the prediction would not, at first. Surge forecasting needs enough historical trips per zone to learn a pattern, and a small fleet does not generate that for months. Start with road-network dispatch, which helps immediately, and switch the prediction on once there is history to train it on.'],
        ['q' => 'Can it integrate with an existing driver app?',
         'a' => 'Usually yes, if the app can report position and accept an assignment over an API. The dispatch engine does not need to own the driver experience. Replacing a driver app that drivers already have installed and trust is a change-management problem worth avoiding where the existing one is adequate.'],
        ['q' => 'How is pricing kept auditable?',
         'a' => 'Every fare stores the inputs that produced it — distance, duration, surge multiplier at the moment of booking, and the rule version in force. A rider disputing a fare six weeks later can be answered from the record rather than from a recalculation, which will not match because conditions have changed.'],
        ['q' => 'What would you do differently starting again?',
         'a' => 'Build the support console at the same time as the rider app rather than after it. Every marketplace ships with the assumption that operations can be handled in the database for a while, and every one of them discovers within a month that it cannot. The tooling for humans to intervene is product, not an internal nicety.'],
    ],

    /* ---- Toing — food delivery ------------------------------------------ */
    'toing-food-delivery' => [
        ['q' => 'What does "habit-based" recommendation mean in practice?',
         'a' => 'It weights when you order as heavily as what you order. Food ordering is strongly patterned — the Friday order is not the Tuesday lunch order, and the same person wants different things at those two moments. A model that only knows your item history recommends your most-ordered dish at every hour, which is why generic recommenders underperform here.'],
        ['q' => 'How did that lift repeat orders?',
         'a' => 'Mostly by shortening the path to a reorder. The gain came from putting the right four options on the first screen at the right time of day rather than from discovering novel dishes. Reducing the decision from a browse to a tap is what moves repeat rate; recommendation is the mechanism, not the goal.'],
        ['q' => 'Does it need a lot of data before it works?',
         'a' => 'It needs a few orders per customer, not a lot of customers. Cold-start users get time-of-day and locality popularity, which is a decent baseline, and the personal signal takes over after roughly three or four orders. A platform with thousands of one-time users and few returners will not see much from this.'],
        ['q' => 'How are delivery routes assigned?',
         'a' => 'Dynamically, by batching orders that share a direction and a ready-time window rather than assigning each order as it arrives. The constraint that matters most is kitchen ready-time, not distance — a rider dispatched to a restaurant that is eleven minutes from plating is a rider standing still.'],
        ['q' => 'Why Flutter for the app?',
         'a' => 'One codebase across both platforms with near-native performance, which matters for a consumer app where the menu, cart and tracking screens must feel instant. For a product whose competitive surface is speed of ordering rather than deep platform integration, the maintenance saving is worth more than the last few percent of native polish.'],
        ['q' => 'How do you keep live order tracking accurate?',
         'a' => 'By reporting state changes from the source of truth rather than estimating them. The rider app reports position, the restaurant confirms preparation and pickup, and the customer sees the actual state. An ETA that is a countdown with nothing behind it is worse than no ETA, because it destroys trust the first time it is wrong.'],
        ['q' => 'What does this cost to run at low volume?',
         'a' => 'The recommendation is cheap — it is a trained model doing inference, not a large language model per request. The expensive parts of a delivery platform at low volume are the human ones: support, rider supply and restaurant onboarding. Technology is rarely the constraint on a small delivery business.'],
        ['q' => 'Can restaurants manage their own menus?',
         'a' => 'Yes, and they must, or the platform becomes a data-entry service. Menu, pricing and availability are restaurant-owned with an approval step, and item-level availability toggling is the single most-used feature in any restaurant console — running out of a dish is a several-times-a-day event.'],
        ['q' => 'How do you handle refunds and missing items?',
         'a' => 'With a policy encoded in the platform rather than decided per case in a support chat. Missing-item claims have to be resolvable in one step with a clear rule about who absorbs the cost — the restaurant, the rider or the platform — otherwise support becomes the bottleneck and the rule becomes whoever complains loudest.'],
        ['q' => 'Would you build this the same way today?',
         'a' => 'Largely, with one change: instrument the funnel from the first day rather than adding analytics once the product works. Knowing where ordering is abandoned is what made the recommendation work, and that data only exists if it was being collected before anyone thought to ask the question.'],
    ],

    /* ---- Urimai Kural — civic grievances -------------------------------- */
    'urimai-kural' => [
        ['q' => 'Why do grievances need automatic routing at all?',
         'a' => 'Because manual triage is where public complaint systems fail. A citizen describes a problem in their own words; a clerk has to decide which of forty departments owns it. That queue grows faster than it clears, and a complaint sitting unrouted for eleven days is indistinguishable to the citizen from one that was ignored.'],
        ['q' => 'How accurate is the categorisation?',
         'a' => 'Good enough to route, not good enough to be unsupervised, and the design reflects that. Confident classifications route directly; ambiguous ones go to a human queue with the model\'s best two guesses attached. The value is in removing the eighty percent that are obvious, not in pretending the remainder does not need judgment.'],
        ['q' => 'How does the voice part work?',
         'a' => 'Whisper transcribes the recording, and the text goes through the same classifier as a typed grievance. Voice matters here for a reason that has nothing to do with technology: a citizen who is not comfortable writing a formal complaint will record one, and excluding them excludes exactly the people the system exists for.'],
        ['q' => 'Does it work in Tamil?',
         'a' => 'Yes, including spoken Tamil and the mixed Tamil-English most people actually use. Handling code-switching properly is not optional in this context — a grievance that switches language mid-sentence is the normal case, not the edge case, and a pipeline that only handles clean monolingual input will drop a large share of real submissions.'],
        ['q' => 'What stops officers ignoring what they are assigned?',
         'a' => 'Visibility and an escalation clock. Every grievance has an owner, an age and a status that the citizen can see, and unactioned items escalate upward automatically. The technology cannot create accountability, but it can remove the ambiguity that accountability usually hides behind.'],
        ['q' => 'How is citizen privacy handled?',
         'a' => 'Contact details are separated from the grievance body and visible only to the assigned officer, and recordings are retained under a fixed policy rather than indefinitely. A civic system holds complaints about powerful people from people with less power, and treating that record casually is the risk that matters most here.'],
        ['q' => 'Why is there a PHP admin bridge in the stack?',
         'a' => 'Because the department already had one, and replacing a working internal system that staff know is a cost with no benefit to the citizen. The new platform integrates with it rather than demanding a migration. Insisting on a clean stack at the expense of adoption is how good civic software goes unused.'],
        ['q' => 'Could this work for a different municipality?',
         'a' => 'The pipeline transfers; the taxonomy does not. Categories, departmental ownership and escalation rules are specific to how a given body is organised, and that mapping is a few weeks of work with someone who genuinely knows the structure. The classifier then has to be retrained against that taxonomy on real local submissions.'],
        ['q' => 'What happens when the model classifies something wrongly?',
         'a' => 'The receiving officer reassigns it in one action, and the correction is recorded as training signal. The important design decision is that reassignment is cheap and obvious — if correcting a misroute takes more effort than handling it, officers will handle it, and the routing quietly stops improving.'],
        ['q' => 'What was the hardest part of this project?',
         'a' => 'Getting agreement on who owns what. A surprising share of grievances legitimately belong to two departments, and the platform forced a decision that had previously been resolved by both ignoring it. That is an organisational outcome rather than a technical one, and it took longer than the machine learning.'],
    ],

    /* ---- DE Drone World — academy platform ------------------------------- */
    'de-drone-world' => [
        ['q' => 'What was manual before this platform?',
         'a' => 'Admissions, contracts and bookings all ran through email and spreadsheets. A prospective pilot enquired, someone replied with a fee structure, a contract went back and forth as an attachment, and payment was reconciled by hand. Each step worked; together they capped how many students the academy could take without hiring administrators.'],
        ['q' => 'What does "contract lifecycle management" mean here?',
         'a' => 'Generating the right contract for the course and student, getting it signed, storing it against the enrolment, and knowing which are outstanding. The last part is the one that pays for itself — the failure mode in a training business is not an unsigned contract, it is nobody knowing which contracts are unsigned.'],
        ['q' => 'How are payments handled?',
         'a' => 'Razorpay, with the payment tied to the enrolment record rather than reconciled separately. Instalments matter for courses at this price point, so the schedule, what has been paid, and what is due sit on the student record where admissions staff can see them without opening a payment dashboard.'],
        ['q' => 'Does it handle DGCA compliance requirements?',
         'a' => 'It holds the records that compliance depends on — enrolments, course completion, documents — in a form that can be produced on request. It is not a certification authority and does not claim to interpret regulation for you. Where a rule changes, the record structure adapts; the obligation stays with the academy.'],
        ['q' => 'Why Django rather than something lighter?',
         'a' => 'The admin is most of the product. A training academy needs staff to create courses, correct enrolments, reissue contracts and fix mistakes constantly, and Django gives a credible admin on day one that would otherwise be months of bespoke CRUD. The public-facing site is the smaller half of this build.'],
        ['q' => 'How long did it take?',
         'a' => 'A few months to the full platform, but the admissions flow was live well before the rest. Sequencing matters on a build like this: admissions relieves the pressure that justified the project, so shipping it first funds attention for the contract and booking work that follows.'],
        ['q' => 'Can it handle multiple course types and batches?',
         'a' => 'Yes — courses, batches, capacity and pricing are data rather than code, because a training business changes its offering constantly. Anything an academy will plausibly change twice a year has to be editable by staff, or the platform becomes a change-request queue pointed at us.'],
        ['q' => 'What about the commercial drone service bookings?',
         'a' => 'They run through the same platform with a different workflow: enquiry, scoped quote, scheduling and invoice. Keeping training and services in one system matters because they share customers and equipment, and splitting them across two tools is how double-booked pilots happen.'],
        ['q' => 'Would this suit a smaller academy?',
         'a' => 'The admissions and contract parts, yes, and they are the parts that hurt first. The scheduling and commercial-services modules only earn their keep past a certain volume. We would rather scope a smaller academy to the first half than sell a platform whose second half sits unused.'],
        ['q' => 'What is the maintenance burden?',
         'a' => 'Modest, and it is mostly course and content changes staff make themselves. The genuine maintenance cost in a platform like this is payment gateway and regulatory change, neither of which is predictable, which is why we would rather have a small retainer than a support contract that pretends the year is quiet.'],
    ],

    /* ---- Central Adventures — tour itineraries --------------------------- */
    'central-adventures' => [
        ['q' => 'What makes an educational tour quote hard to produce?',
         'a' => 'Every input is a variable. Group size, age band, duration, destinations, transport, accommodation grade and meal plan all move together, and a change to any one of them changes the price of the others. A staff member doing this in a spreadsheet takes hours per enquiry and makes arithmetic errors under deadline.'],
        ['q' => 'How does the portal build an itinerary automatically?',
         'a' => 'From a rules-and-components model, not from generative text. Destinations, activities and transfers are components with durations, costs and compatibility constraints; the portal assembles a feasible sequence for the given group and dates and prices it. The result is defensible, which a generated paragraph is not.'],
        ['q' => 'Can staff override what it produces?',
         'a' => 'Always, and they do on roughly every enquiry. The portal gets a school from nothing to a credible priced draft in minutes; a human then adjusts for the things a rules engine does not know, like a principal who wants the museum on the first day. Automating the first eighty percent is the win.'],
        ['q' => 'Why WeasyPrint in the stack?',
         'a' => 'Because the quote has to become a PDF that a school committee will read and approve, and it has to look like a document rather than a web page printed badly. Schools circulate these internally, and a proposal that formats poorly loses to one that does not, whatever the itinerary says.'],
        ['q' => 'How are prices kept current?',
         'a' => 'Component costs are data with effective dates, so a quote issued in March is priced on March\'s rates and can be reproduced later. The alternative — costs hard-coded and updated by hand each season — is how a travel business ends up honouring a quote it can no longer afford.'],
        ['q' => 'Does it handle payments?',
         'a' => 'Yes, through Razorpay, with the deposit and balance structure schools actually use. Group travel is rarely paid in one transaction, and a payment model that assumes it is creates reconciliation work that swallows the time the automation saved.'],
        ['q' => 'How long did this take to build?',
         'a' => 'A couple of months, and most of that was encoding the pricing rules rather than building the portal. The rules existed only in the heads of two experienced staff, and getting them written down precisely enough to execute is the genuinely slow part of any quoting automation.'],
        ['q' => 'Would this work for a different kind of travel business?',
         'a' => 'If your product is assembled from components and priced by rules, yes — the shape transfers to corporate offsites, pilgrimages and adventure operators. If every trip is bespoke and priced by negotiation, this is the wrong tool and a good CRM would serve you better.'],
        ['q' => 'What happened to the staff who used to produce quotes?',
         'a' => 'They handle more enquiries and spend the time on the part that wins the business, which is the conversation with the school rather than the arithmetic. This is worth saying plainly: the goal was throughput on a constrained team, not headcount reduction, and that is what it delivered.'],
        ['q' => 'What would you change if starting again?',
         'a' => 'Model the components before writing any interface. We began with the portal and discovered the pricing model needed restructuring halfway through, which cost rework. In quoting systems the data model is the product and the screens are a thin layer over it.'],
    ],

    /* ---- Cute Crew — kids e-commerce ------------------------------------ */
    'cute-crew' => [
        ['q' => 'Why are returns so high in children\'s fashion?',
         'a' => 'Because parents buy for a moving target. A child\'s size changes between order and delivery, brand sizing is inconsistent, and a parent shopping for a four-year-old is guessing against a label rather than a measurement. Most returns are fit, not quality, and fit is a solvable information problem.'],
        ['q' => 'How does the fit engine work?',
         'a' => 'It maps the child\'s age and measurements against the actual garment measurements of each SKU, learning from what was kept and what came back. The critical input is per-SKU garment measurements rather than the size label, because the label is exactly the thing that is inconsistent between brands.'],
        ['q' => 'Did returns really drop by that much?',
         'a' => 'The figure is the client\'s, measured against their own pre-launch baseline, and the mechanism is unglamorous. A meaningful part of it came simply from showing the garment\'s real measurements and a plain recommendation on the product page, before any personalisation applied.'],
        ['q' => 'What data do you need to build this?',
         'a' => 'Garment measurements per SKU and return reasons per order. Most storefronts have neither — return reasons are usually a free-text box nobody analyses. Capturing a structured reason at return is the cheapest thing a fashion retailer can do, and it has to happen months before a model is worth training.'],
        ['q' => 'How long until it is better than a size chart?',
         'a' => 'The rules-based version beats a size chart immediately, because a size chart puts the work on the customer. The learned version needs a few thousand orders with outcomes before it adds much on top. Start with the first, and only build the second once the data justifies it.'],
        ['q' => 'Why Next.js and FastAPI rather than a platform?',
         'a' => 'Because the recommendation sits inside the product page and has to be fast and bespoke. Where a storefront\'s differentiator is a custom model in the buying flow, a headless front end over your own API earns its cost. For a standard catalogue it would not, and we would have said so.'],
        ['q' => 'Does it work for a catalogue that changes every season?',
         'a' => 'Yes, provided new SKUs arrive with measurements. The model generalises across garment types rather than memorising specific products, so a new season is not a cold start. A SKU uploaded without measurements simply falls back to the size chart, which is the incentive to keep the data clean.'],
        ['q' => 'What is the effect on conversion, not just returns?',
         'a' => 'Positive but smaller, and worth separating. Fit confidence reduces abandoned carts somewhat; the substantial gain is on the return side, which is where the margin actually leaks. A project justified on conversion alone would have been a harder case to make.'],
        ['q' => 'Would this work for adult fashion?',
         'a' => 'The mechanism transfers but the economics differ. Adult buyers know their own measurements and reorder from brands they trust, so the information gap is narrower. Children\'s wear is unusual in that the buyer is not the wearer and the wearer changes size continuously.'],
        ['q' => 'What would you do differently?',
         'a' => 'Instrument returns first and build the engine second. We ended up retrofitting structured return capture, which delayed the learned model by a season. If you are considering this, start collecting the reason codes now even if you build nothing else this year.'],
    ],

    /* ---- Lotus Eye Hospital — agentic healthcare ------------------------- */
    'lotus-eye-hospital' => [
        ['q' => 'What does "agentic" mean in a hospital context?',
         'a' => 'That the system carries a patient journey forward across steps rather than waiting to be told what to do next. Booking, intake, consultation notes, billing and pharmacy dispatch are stages of one workflow, and an agent holds the state between them. It is not a model making clinical decisions, and that distinction is the whole design.'],
        ['q' => 'Does the AI diagnose anything?',
         'a' => 'No. It transcribes, structures, routes and schedules. Clinical judgment stays with the clinician, every generated note is reviewed before it enters the record, and nothing in the system recommends a treatment. We would decline to build the alternative.'],
        ['q' => 'How accurate is the AI scribe?',
         'a' => 'Good enough to draft, and it is always a draft. Whisper handles the transcription including accented English and code-switching, and the structuring into a note is checked by the clinician before it is saved. The time saved is in typing, not in thinking, and a scribe sold as removing review is a liability.'],
        ['q' => 'Where does patient data live?',
         'a' => 'In the hospital\'s own tenancy, with access scoped by role and every access logged. Audio recordings follow a fixed retention policy rather than accumulating. For anything involving a model provider, the design minimises what leaves the tenancy and records exactly what did.'],
        ['q' => 'How does it integrate with existing hospital systems?',
         'a' => 'Through whatever interface they expose — API where one exists, structured export where it does not. Hospital software is rarely replaceable in one step, so the platform is built to run alongside an incumbent EMR and take over functions gradually rather than demanding a cutover.'],
        ['q' => 'What happens when the video consultation fails?',
         'a' => 'It falls back to audio, then to a phone call, and the consultation record survives all three. Connectivity in a teleconsultation is the most common failure and the least forgivable, because the patient has already waited. The system is designed around the call failing rather than around it working.'],
        ['q' => 'How long did this take?',
         'a' => 'This is a multi-month platform, and it was built in stages with each one live before the next began. Booking and consultation came first, billing and pharmacy after. A big-bang hospital rollout is how these projects fail, because staff cannot absorb that much change at once and will revert to paper.'],
        ['q' => 'What was the hardest part?',
         'a' => 'Adoption, not engineering. Clinicians have workflows refined over years and a system that adds a step will be abandoned regardless of what it saves elsewhere. Most of the design iteration went into removing clicks from the consultation screen, which is the only screen a doctor actually lives in.'],
        ['q' => 'Would this suit a single-doctor clinic?',
         'a' => 'Parts of it. The scribe and booking make sense at any size; EMR, billing and pharmacy orchestration only pay back where there is a multi-person operation to coordinate. A single practitioner is usually better served by a good off-the-shelf clinic tool than by a platform.'],
        ['q' => 'What are the ongoing costs?',
         'a' => 'Hosting, transcription and inference, and transcription dominates because consultations are long. Routing transcription to a smaller model where audio is clean and reserving the larger one for difficult recordings cut that materially. We model it per consultation so the cost scales with activity rather than with a seat count.'],
    ],

    /* ---- Coonoor Club — member portal ------------------------------------ */
    'coonoor-club' => [
        ['q' => 'What was the club running on before?',
         'a' => 'Ledgers, phone calls and a member list that lived in more than one place. Nothing was broken exactly — a heritage club with long-standing members runs on staff knowledge — but renewals were chased manually, bookings were a phone conversation, and the wallet balance a member asked about took someone walking to a file.'],
        ['q' => 'Why a wallet rather than pay-per-booking?',
         'a' => 'Because it is how clubs already work. Members hold a running balance, spend against it at the bar and restaurant, and top it up periodically. Modelling the software on the existing financial habit rather than imposing a transaction-per-booking model is why members adopted it.'],
        ['q' => 'How are bookings for rooms, tables and the bar kept consistent?',
         'a' => 'One availability model underneath, three interfaces on top. They look like separate products to a member but they contend for the same resources and the same member balance, and building them as three systems is how a table gets double-booked on a busy evening.'],
        ['q' => 'What happens to members who will not use a portal?',
         'a' => 'Staff enter on their behalf, and that path is a first-class feature rather than a workaround. A club with members in their seventies cannot make digital the only channel, and a system that forces it produces a parallel paper process that immediately diverges from the database.'],
        ['q' => 'How is membership renewal automated?',
         'a' => 'Dues are scheduled against each member record with reminders ahead of the date and a payment link, and staff see who is outstanding on one screen. The automation that mattered was not the payment — it was replacing a manual list of who had not paid, which was always slightly wrong.'],
        ['q' => 'Is the member data secure?',
         'a' => 'Access is role-scoped and financial actions are logged against the staff member who performed them. In a club the risk is rarely an external attacker; it is an internal adjustment nobody can later explain, and an audit trail on wallet transactions is what prevents that becoming a dispute.'],
        ['q' => 'How long did it take?',
         'a' => 'A few months, with the member portal first and staff tooling following. The order was deliberate: members using the portal creates the pressure that gets staff processes migrated, whereas staff tooling built first tends to become a nicer version of the old workflow.'],
        ['q' => 'Could another club reuse this?',
         'a' => 'Substantially, yes — wallets, bookings and renewals are common to most clubs. What differs is the rules: who may book what, guest policies, subscription categories and the arithmetic of dues. Those are configuration, but they take a genuine conversation with the committee to pin down.'],
        ['q' => 'What does it cost to run?',
         'a' => 'Small. It is a Django application on modest hosting with a payment gateway, and a club of this size does not generate load worth optimising for. The recurring cost that matters is a support arrangement for when a payment or a booking goes wrong on a Saturday evening.'],
        ['q' => 'What did the club gain that it did not expect?',
         'a' => 'Visibility of usage. Once bookings were data, the committee could see which facilities were actually used and when, which had previously been a matter of opinion. That has more influence on club decisions than the convenience the project was justified on.'],
    ],

    /* ---- Jaumo — dating app ---------------------------------------------- */
    'jaumo' => [
        ['q' => 'What is wrong with swipe-based matching?',
         'a' => 'It optimises for the photograph, which predicts a match and not a conversation. The outcome users want is a second date; the outcome swiping selects for is attractiveness at a glance. Building for compatibility means accepting fewer matches with a better conversion into real conversations.'],
        ['q' => 'How does the compatibility matching work?',
         'a' => 'From a personality and preference model built out of onboarding responses and refined by behaviour — who people actually talk to, not who they say they want. Stated preference and revealed preference diverge sharply in dating, and a model that trusts the stated version recommends people nobody messages.'],
        ['q' => 'What is Blind Date mode?',
         'a' => 'A conversation that starts without photographs, with the profile revealed after a genuine exchange. It exists to test the premise directly: if compatibility beats appearance, removing appearance from the first impression should improve conversation quality. It is a product position as much as a feature.'],
        ['q' => 'How do you handle safety and abuse?',
         'a' => 'Reporting, blocking, rate limits and moderation review, built in from the start rather than added after an incident. A dating platform will be used to harass people, and treating that as an edge case is the single most common failure in this category. The report flow has to be faster than the abuse.'],
        ['q' => 'Does it need a large user base to work?',
         'a' => 'More than most products, yes, and this is the honest constraint. Matching quality depends on liquidity in a given city and age band. A compatibility model cannot rescue a market with two hundred users; launching city by city with density is the only approach that works.'],
        ['q' => 'Why real-time messaging over WebSockets?',
         'a' => 'Because delivery latency is felt directly in a conversation. In most products a second of lag is invisible; in a chat where someone is deciding whether the other person is interested, it reads as hesitation. It is one of the few places where the transport choice is a product decision.'],
        ['q' => 'How is the matching kept from becoming a filter bubble?',
         'a' => 'By reserving a share of recommendations for exploration rather than exploitation. A model that only shows you people like the ones you already liked converges quickly and then stops producing matches. Deliberate diversity in the slate is what keeps the pool from collapsing.'],
        ['q' => 'What does it cost to run?',
         'a' => 'Messaging infrastructure and image storage dominate, and both scale with active users rather than registered ones. The matching model itself is inexpensive — it is trained periodically and served from cache, not computed per view.'],
        ['q' => 'How do you measure whether matching improved?',
         'a' => 'By conversations that pass a real threshold — a genuine exchange of several messages, or a reported meeting — not by match count. Match count is trivially inflatable and every dating product that reports it is choosing the flattering metric over the useful one.'],
        ['q' => 'Would you build a dating product again?',
         'a' => 'Yes, with a clearer position from the outset. The products that survive in this category stand for something specific about how they match; the general-purpose ones compete on marketing spend against incumbents with enormous budgets. The technology was never the hard part.'],
    ],

    /* ---- Mehala Carona — textile ERP ------------------------------------- */
    'mehala-carona' => [
        ['q' => 'Why build an ERP rather than buy one?',
         'a' => 'Because the parts that mattered were the parts no package covers. Standard ERP handles finance and inventory well; it does not handle this mill\'s machinery maintenance schedules, its production tracking or its export documentation without heavy customisation. When the customisation is most of the system, a package is the more expensive route.'],
        ['q' => 'Is a monolith the right choice in 2026?',
         'a' => 'For this, yes. Production, sales, HR and shipping share entities constantly, and a microservice split would have turned every ordinary query into a distributed join maintained by a team the client does not have. Architecture should match the organisation that has to run it, and a single well-structured application was correct here.'],
        ['q' => 'What does the AI part actually do?',
         'a' => 'Machinery maintenance prediction and data pipeline work. Airflow moves and reconciles data from the floor, and models flag machines whose sensor and downtime patterns resemble the run-up to previous failures. It schedules a check sooner; it does not decide to stop a machine.'],
        ['q' => 'How accurate is the maintenance prediction?',
         'a' => 'Useful rather than precise, and the honest framing is that it changes the order of an existing maintenance queue rather than predicting a date. Its value is avoiding the unplanned stoppages that cost a shift. Anyone quoting a failure date to the day on textile machinery is overselling.'],
        ['q' => 'How long does an ERP like this take?',
         'a' => 'Many months, module by module, and it is never finished. That is not a caveat — an ERP tracks how a business runs, and a business that stops changing is in trouble. Budget for continuing development rather than a project with an end date, or the system will drift away from the operation within two years.'],
        ['q' => 'How did you handle the migration from the old system?',
         'a' => 'In parallel, with the old system authoritative until each module was proven. Cutting over a manufacturer\'s records in one weekend is an unacceptable risk when a failed migration means not knowing what is on the floor. The duplication costs weeks; the alternative costs the business.'],
        ['q' => 'Does it handle export documentation?',
         'a' => 'Yes — the shipping logistics module covers the documentation an international textile shipment requires, generated from the order data rather than retyped. Re-entry is where export errors come from, and an error in export paperwork is expensive in a way an internal mistake is not.'],
        ['q' => 'What about staff who are not comfortable with software?',
         'a' => 'The floor interfaces were designed for the floor: few fields, large targets, and workable on the devices that are actually there. The office modules can be dense because office staff use them all day. Applying one interface standard across both is how ERPs end up bypassed on the shop floor.'],
        ['q' => 'Would this suit a smaller manufacturer?',
         'a' => 'Not the whole thing. A smaller mill should take production tracking and inventory and leave the rest, because the coordination cost that justifies an integrated ERP does not exist below a certain size. We would scope that down rather than sell a platform that mostly sits idle.'],
        ['q' => 'What is the biggest risk with a build like this?',
         'a' => 'Dependence on a single vendor. We mitigate it deliberately: documented code, the client\'s own repository, standard technologies with a hiring market, and a handover that assumes another team will maintain it. An ERP a business cannot take elsewhere is a liability regardless of quality.'],
    ],

    /* ---- Madura Grandeur — hotel site ------------------------------------ */
    'madura-grandeur' => [
        ['q' => 'Why a direct booking request rather than a booking engine?',
         'a' => 'Because it matches how this property actually sells. Banquet and group enquiries need a conversation, and an instant-confirmation engine adds a commission and a rigidity that does not fit. A request form that reaches the front desk fast, with the room and dates attached, converts well at this scale.'],
        ['q' => 'Why publish tariffs at all?',
         'a' => 'Because hiding them loses the booking. A guest comparing hotels will skip one that makes them ask, and the enquiries a hidden tariff generates are mostly people who would not have booked at that price anyway. Published rates cost a little rate flexibility and buy a great deal of qualified traffic.'],
        ['q' => 'How does this compete with the online travel agents?',
         'a' => 'It does not replace them; it makes the direct channel viable alongside them. Guests routinely find a hotel on an aggregator and then check the hotel\'s own site before booking. If that site is slow, dated or silent on price, the booking goes back to the aggregator and the commission with it.'],
        ['q' => 'Why a static site rather than a CMS?',
         'a' => 'Because the content changes a few times a year and the site has to be fast and cheap to run. A CMS on a small hotel site is usually an unpatched attack surface maintained by nobody. Where the update rhythm is seasonal, a built site on a CDN is the more durable choice.'],
        ['q' => 'How do staff update tariffs or add photographs?',
         'a' => 'Through a defined handover process rather than an admin panel, which suits a property that updates seasonally. Where a client wants day-to-day control we fit a lightweight CMS instead — but it should be a decision, not a default, because the ongoing cost lands on them either way.'],
        ['q' => 'Does it work properly on a phone?',
         'a' => 'It is built for the phone first, because that is where hotel searching happens. The gallery, tariffs and the booking request are all designed for a thumb on a moving bus with poor signal, which is a harsher constraint than any desktop layout.'],
        ['q' => 'How long did it take?',
         'a' => 'Weeks, not months. The bulk of the schedule on a hotel site is photography and copy, not engineering — a property that already has good photographs moves fast, and one that does not should budget for a shoot before anything else.'],
        ['q' => 'What about SEO for a local hotel?',
         'a' => 'Speed, clean structure, honest local signals and a Google Business Profile that matches the site. For a single-property hotel the returns come from being unambiguously findable for the town and the category, not from content volume. A blog is usually the wrong investment here.'],
        ['q' => 'Can it add rooms or a new banquet hall later?',
         'a' => 'Yes, and cheaply, because the templates are structured rather than hand-built per page. Adding an inventory type is a content change, not a rebuild. That is the test of whether a small site was built properly.'],
        ['q' => 'What is the ongoing cost?',
         'a' => 'Close to nothing in hosting, plus whatever content updates you want. That is the point of the architecture choice: a small hotel should not carry a monthly platform bill for a site that changes with the season.'],
    ],

    /* ---- Bharani Beauty Clinic — parlour site ----------------------------- */
    'bharani-beauty-clinic' => [
        ['q' => 'Does a parlour that has run since 1988 need a website?',
         'a' => 'It needs to be findable and checkable, which is what the site does. Word of mouth still brings the customers; what changed is that a bride now searches, compares and reads reviews before calling. A parlour with thirty-five years of reputation and no web presence loses to a newer one with photographs.'],
        ['q' => 'What does the site actually need to achieve?',
         'a' => 'Get someone to call or message. Bridal and beauty bookings are conversations, not checkouts, so the site\'s job is to establish that the work is good, the place is real, and the contact details are one tap away. Anything beyond that is decoration on a business of this shape.'],
        ['q' => 'Why lead with the history?',
         'a' => 'Because longevity is the strongest signal this business has. A parlour trading since 1988 has survived every competitor that opened nearby, and for a bride choosing where to spend the most photographed day of her life, that is more persuasive than any claim about technique.'],
        ['q' => 'Why a website builder rather than a custom build?',
         'a' => 'Because it is the right tool for the job and we will say so. A local parlour needs a fast, credible, mobile-friendly presence it can afford and eventually edit itself. Selling a bespoke build here would have been selling a cost with no return, and the money is better spent on photography.'],
        ['q' => 'How important are the photographs?',
         'a' => 'They are the product. In beauty services the portfolio is the argument, and a well-built site with weak photographs will underperform a plain site with strong ones. The single highest-return investment for any parlour considering this is a proper shoot of real work.'],
        ['q' => 'Do the reviews on the site help?',
         'a' => 'Yes, provided they are real and attributable. Named, specific reviews about a particular service carry weight; anonymous five-star quotes read as invented and can do net harm. The ones worth surfacing are the detailed ones, not the most flattering ones.'],
        ['q' => 'How does someone in Gobichettipalayam find this?',
         'a' => 'Mostly through Google Maps and a local search, which is why the site\'s job is to match and reinforce the Business Profile rather than to compete with it. Consistent name, address, phone and service list across both is worth more than any amount of on-page optimisation.'],
        ['q' => 'Can the parlour update it themselves?',
         'a' => 'Yes — that is part of why the builder was the right choice. Adding a new service or a fresh set of photographs should not require us, because on a business this size it would simply not happen. A site only the developer can edit becomes a site nobody edits.'],
        ['q' => 'Should there be online booking?',
         'a' => 'Not yet, and possibly not at all. Bridal work is scoped and priced in conversation, and an online slot booking would create appointments that have to be re-negotiated anyway. Where volume services like threading or facials grow enough to justify it, that is the moment to add it.'],
        ['q' => 'What would you recommend next for a business like this?',
         'a' => 'Photography, then reviews, then the site. Most local service businesses have the order backwards and spend on a website while their portfolio and their Business Profile go untended. The site amplifies whatever those two are; it cannot substitute for them.'],
    ],

    /* ---- Aruvanaa — agri-commodity export -------------------------------- */
    'aruvanaa' => [
        ['q' => 'Why does a commodity trader need a website at all?',
         'a' => 'To survive the check that happens before the first call. A UAE buyer sourcing from India is taking a risk on an unfamiliar counterparty, and they will look the company up. A trader with no credible web presence is indistinguishable from an intermediary with no goods, whatever the reality.'],
        ['q' => 'What has to be on it to establish credibility?',
         'a' => 'Registration details, the actual commodities handled, the supply-chain services provided, compliance and certification credentials, and a real address and contact. Vague claims about quality and partnership are what every unproven intermediary writes; specifics are what distinguish a real exporter from one.'],
        ['q' => 'Why emphasise compliance credentials so heavily?',
         'a' => 'Because they are the qualifying criterion. Agricultural commodities crossing a border face inspection, documentation and standards requirements, and a buyer\'s first filter is whether you can clear them. Compliance is not a trust badge here, it is the product specification.'],
        ['q' => 'Does it need to be in Arabic?',
         'a' => 'Business in this corridor is conducted in English and the site serves its purpose without it. Translation becomes worthwhile if the buyer base shifts toward parties who prefer Arabic for documentation — and a badly machine-translated site is worse than an English one, so it is a real investment, not a checkbox.'],
        ['q' => 'Why React and Vite for a corporate site?',
         'a' => 'Component reuse across a structured catalogue of commodities and services, and a fast build. For a site of this size it is a matter of maintainability rather than necessity — the same result is achievable several ways, and the choice mattered less than the content did.'],
        ['q' => 'How do buyers find a site like this?',
         'a' => 'Rarely by search, mostly by referral and verification. The site is the destination of a check, not the top of a funnel. Optimising it for volume traffic would be optimising for the wrong visitor; optimising it to answer a serious buyer\'s questions in ninety seconds is correct.'],
        ['q' => 'Should it publish prices?',
         'a' => 'No. Commodity prices move daily and are quoted per consignment against grade, volume and delivery terms. A published price is either instantly stale or so hedged that it means nothing. This is the one category where withholding price is genuinely right.'],
        ['q' => 'How long did it take?',
         'a' => 'Weeks. As with most corporate sites the schedule is set by how quickly the company can confirm its own details — certifications, capabilities, the exact commodity list — rather than by the build.'],
        ['q' => 'What is the most common mistake on trader websites?',
         'a' => 'Claiming everything. A site listing forty commodities and every service in the chain reads as a broker with no operations. Naming what you actually move and what you actually do is more persuasive to a professional buyer, who can tell the difference immediately.'],
        ['q' => 'What would you add next?',
         'a' => 'Evidence. Shipment records, facility photographs, named certifications with numbers, and specifics of past consignments where confidentiality permits. Credibility for a trading business comes from verifiable detail, and that is the gap on almost every site in the sector.'],
    ],

    /* ---- AERON — drone training platform ---------------------------------- */
    'aeron' => [
        ['q' => 'What problem does a drone school have that this solves?',
         'a' => 'Proof. An RPTO has to evidence who trained, on what, for how long, and that the records are intact — and most run this on spreadsheets and paper logbooks. The platform makes the logbook the system of record rather than a thing reconstructed before an audit.'],
        ['q' => 'What is the 3D flight replay for?',
         'a' => 'Instruction, mainly. A student who is told their approach was unstable learns less than one who watches the track and sees where it went wrong. It also makes a logbook entry checkable — a flight with a replay behind it is evidence in a way a handwritten line is not.'],
        ['q' => 'Is the browser simulator a real training tool?',
         'a' => 'It is a familiarisation tool, and worth being precise about that. It builds control intuition and lets a student practise procedure before touching an aircraft, which saves airframe time and instructor hours. It does not substitute for logged flight and we would not present it as doing so.'],
        ['q' => 'Why three.js in the browser rather than a native application?',
         'a' => 'Because it has to be used, and anything requiring an install on a student\'s machine will not be. A simulator and a replay that open from a link get used between sessions; a download gets opened once. The fidelity trade is worth the reach at this level of training.'],
        ['q' => 'Does it keep DGCA-compliant records?',
         'a' => 'It holds the training and flight records in a structured, exportable form suitable for the evidence an RPTO must produce. It is not a regulator, it does not certify anyone, and where the rules change the record structure is adapted. The compliance obligation remains the school\'s.'],
        ['q' => 'Why build it as a PWA?',
         'a' => 'Because flight training happens at airfields where connectivity is poor. A progressive web app installs like an app, works offline and syncs when signal returns, which matters when a logbook entry is made in a field rather than in an office.'],
        ['q' => 'Can multiple schools use it?',
         'a' => 'It is built for a school to run its own students, instructors and fleet. Multi-tenant operation is a natural extension but has real implications for data separation and record custody, and that is a decision to take deliberately rather than as an afterthought.'],
        ['q' => 'What about the pilots after they qualify?',
         'a' => 'The logbook is theirs and stays useful. A pilot accumulating hours across employers needs a continuous record, and a logbook locked to the school they trained at is worth much less than one that travels with them. Export is a first-class feature for that reason.'],
        ['q' => 'How long did it take?',
         'a' => 'The replay and simulator were the long poles — flight data handling and 3D work take longer than records management, which is comparatively well-trodden. It was built in that order deliberately, so the distinctive part was proven before the routine part was polished.'],
        ['q' => 'Would this suit a small school with two instructors?',
         'a' => 'The logbook and records, yes, immediately. The simulator and replay earn their cost where there is enough throughput for saved airframe time to add up. A two-instructor school should take the records half and revisit the rest when volume justifies it.'],
    ],
];
